PieShopProject/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using PieShopProject.Models;
using System.Diagnostics;

namespace PieShopProject.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        //public IActionResult Error()
        //{
        //    return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        //}

        public IActionResult About()
        {
            return View();
        }
    }
}

PieShopProject/Controllers/PieController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using PieShopProject.DataAccess.Data;
using PieShopProject.DataAccess.Repository;
using PieShopProject.DataAccess.Repository.IRepository;
using PieShopProject.Models.Models;

namespace PieShopProject.Controllers
{
    public class PieController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly PieShopDBContext _db;
        private readonly IWebHostEnvironment _webHostEnvironment;
        

        public PieController(IUnitOfWork unitOfWork, PieShopDBContext db, IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _webHostEnvironment = webHostEnvironment;
            _db = db;

        }
        public IActionResult Index()
        {
            var Pies = _unitOfWork.Pie.GetAll();
            return View(Pies);
        }
        //[HttpGet]
        //public async Task<ActionResult> Index(string Empsearch)                  //for search
        //{
        //    var Pies = _unitOfWork.Pie.GetAll();
        //    ViewData["GetPieDetails"] = Empsearch;
        //    var empquery = from x in _db.Pies select x;
        //    if (!string.IsNullOrEmpty(Empsearch))
        //    {
        //        empquery = empquery.Where(x => x.Name.Contains(Empsearch));
        //    }
        //    return View(empquery.ToString());
        //}


        //  [HttpGet]
        public IActionResult Create()
        {
            

            return View();
        }

        //Create- Post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Pie catObj,IFormFile file)
        {

            if (ModelState.IsValid)
            {
                string path = _webHostEnvironment.WebRootPath;
                if (file != null)
                {
                    // string fileName = Guid.NewGuid().ToString();
                    string ImageName = System.IO.Path.GetFileName(file.FileName);
                    //var uploads = Path.Combine(path, @"Images");
                    //var extentions = Path.GetExtension(file.FileName);
                    catObj.Image = @"/Images/" + ImageName;
                }
                _unitOfWork.Pie.Add(catObj);

                _unitOfWork.Save();
                
                TempData["Success"] = "Pie details added successfully";
                return RedirectToAction(nameof(Index));
            }
            else
            {
                

                return View(catObj);
            }


        }

        public IActionResult Menu()
        {


            var Pies = _unitOfWork.Pie.GetAll();
            return View(Pies);
            
        }
        public IActionResult PieDetails(int id)
        {


            var pies = _unitOfWork.Pie.GetFirstOrDefault(c => c.Id == id); // new after adding unit



            return View(pies);

        }


    }
}

PieShopProject/Views/Pie/Create.cshtml
@model PieShopProject.Models.Models.Pie
@{
    ViewData["Title"] = "Create";
}

<form method="post" asp-action="Create" enctype="multipart/form-data">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Add Pie</h2>
            <hr />

        </div>

        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>

        </div>

        <div class="mb-3">
            <label asp-for="Description"></label>
            <input asp-for="Description" class="form-control" />
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>

        <div class="mb-3">
            <label asp-for="Price"></label>
            <input asp-for="Price" class="form-control" />
            <span asp-validation-for="Price" class="text-danger"></span>
        </div>

        <div class="mb-3">
            <label asp-for="Image"></label>
            <input id="uploadFile" type="file" asp-for="Image" name="file" class="form-control" />
            
        </div>

        
        <div class="mb-3">
            <button type="submit" onclick="return ValidateInput()" class="btn btn-primary" style="width:100px">Add</button>
            <a asp-controller="Pie" asp-action="Index" class="btn btn-secondary" style="width:100px">Back</a>
        </div>

    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }





    <script>
        function ValidateInput() {
            if (document.getElementById("uploadFile").value == "") {
                Swal.fire({
                    icon: 'error',
                    title: 'Oops..',
                    text: 'Pleasue uplode an image file!',





                });
                return false;



            }
            return true;
        }
    </script>
}

PieShopProject/Views/Pie/Index.cshtml
@model IEnumerable<PieShopProject.Models.Models.Pie>
@{
    ViewData["Title"] = "Index";
}

<form method="get" asp-action="Index">



   @* <p>
        <input type="search" placeholder="Enter employee Name" value="@ViewData["GetEmployeeDetails"]" name="Empsearch" style="width:500px" />
        <input type="submit" value="Search" class="btn btn-primary" />
        <button asp-controller="Employees" asp-action="Index">Get all Employees</button>
    </p>*@



</form>



<div class="container p-3">
    <div class="row pt-4">
        <div class="col-0">
            <a asp-controller="Pie" asp-action="Create" class="btn btn-primary"><i class="bi bi-plus"></i>Add Pie</a>
        </div>
        






    </div>
    @*<form class="d-flex" style="float:right">
        <input class="form-control me-sm-2" type="text" placeholder="Search">
        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
    </form>*@

    
    
   
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary"></h2>

        </div>
        
        


    </div>

</div>


<table class="table table-bordered table-striped" border="4" style="width:100%">
    <thead>
        <tr>
            <th>
                Pie Id
            </th>
            <th>
                Pie Name
            </th>
            <th>
                Pie Description
            </th>
            <th>
                Pie Price
            </th>
            <th>
                Pie Image
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var c in Model)
        {
            <tr>
                <td>

                    @c.Id
                </td>
                <td>@c.Name</td>
                <td>@c.Description</td>
                <td>@c.Price</td>
                <td>
                    <img src="~@c.Image" alt="SorryDataBase"
                     height="100" width="100"
                     asp-append-version="true" />

                </td>

                

            </tr>
        }
    </tbody>
</table>

PieShopProject/Views/Pie/Menu.cshtml
@model IEnumerable<PieShopProject.Models.Models.Pie>
@{
    ViewData["Title"] = "Menu";
}




<div class="row">
    @foreach (var c in Model)
    { 

        <div class="col-sm-3 p-3  ">
            <img src="~@c.Image" alt="SorryDataBase"
             height="120" width="120"
             asp-append-version="true" />
            <br />
            <h4 style="color:purple;"> @c.Name</h4>

            <p style="color:crimson">
                @c.Description
            </p>
            <p style="color:hotpink;">
                Price :₹  @c.Price
            </p>




            <div class="btn-group m-75" role="group">
                <a class="btn btn-info pl-2" asp-controller="Pie" asp-action="PieDetails" asp-route-id="@c.Id" class="btn btn-info">Details</a>







            </div>



        </div>


    }
   

PieShopProject/Views/Pie/PieDetails.cshtml
@model PieShopProject.Models.Models.Pie
@{
    ViewData["Title"] = "PieDetails";
}

<h1 >Details</h1>

<div class="text-center">
    
    
    <h1><img src="@Model.Image" width="30%"</img></h1>
    <h3 style="color:lightcoral;">@Model.Name</h3>
    <p style="color:purple;">@Model.Description</p>
    <p style="color:purple;">₹@Model.Price</p>
</div>




<div>
    <a asp-controller="Pie" asp-action="Index" class="btn btn-outline-info">Back</a>
</div>

PieShopProject/Views/Shared/_AlertPartialView.cshtml
@if (TempData["Success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["Success"]')
    </script>
    @* <h2>@TempData["Success"]</h2>*@
}
@if (TempData["Error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>



    <script type="text/javascript">
        toastr.error('@TempData["Error"]')
    </script>
    @*  <h2>@TempData["Error"]</h2>*@
}

PieShopProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PieShopProject</title>
    <link rel="icon" type="image/x-icon" href="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTxTg3XfnxSev9VUH1pUrbi2-WnZy8-O_zG0w&usqp=CAU" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PieShopProject.styles.css" asp-append-version="true" />

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/Bootswatchcss.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.10.2/font/bootstrap-icons.min.css" />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.css" />

</head>
<body background="https://tse1.mm.bing.net/th/id/OIP.P9Nw_HxKNIa8S_wxdjbF5AHaEK?w=319&h=180&c=7&r=0&o=5&pid=1.7">

    <header>
        <partial name="_AlertPartialView" />
        <partial name="_NavBarPartial" />

    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
   

    @*<footer class="border-bottom" style="position:absolute; bottom:0;">

        <div class="container">
            &copy; 2022 - PieShop

        </div>
    </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

PieShopProject/Views/Shared/_NavBarPartial.cshtml
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container-fluid">
        
        <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTxTg3XfnxSev9VUH1pUrbi2-WnZy8-O_zG0w&usqp=CAU" width="3%"width />
        <a class="navbar-brand" href="#">Pie Paradise</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarColor01">
            <ul class="navbar-nav me-auto">
                <li class="nav-item">
                    <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="About">About Us</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-light" asp-area="" asp-controller="Pie" asp-action="Menu">Menu</a>
                </li>

                
                <li class="nav-item">
                    <a class="nav-link text-light" asp-area="" asp-controller="Pie" asp-action="Index">Details</a>
                </li>
                
               


            </ul>

        </div>
    </div>
</nav>